name: 'Workflow'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  workflow:
    name: 'Workflow'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: 'utsuki-bot'
          file: Dockerfile.arm
      - name: stop previous container
        run: docker rm -f utsuki-bot
      - name: run
        run: docker run --name utsuki-bot -e DISCORD_TOKEN_UTSUKI=${{ secrets.DISCORD_TOKEN }} -d utsuki-bot
