name: 'Workflow'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-rust:
    name: 'Build Rust'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-unknown-linux-musl

      - name: Configure sccache env var and set build profile to ephemeral build
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo “SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo “RUSTFLAGS=’--cfg profile=ephemeral-build’” >> $GITHUB_ENV

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-unknown-linux-musl --release


  build-docker:
    name: 'Build Docker'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      - name: build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: 'utsuki-bot'
          file: Dockerfile.arm


  deploy:
    name: 'Deploy'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      - name: run
        env:
          DISCORD_TOKEN_UTSUKI: ${{ secrets.DISCORD_TOKEN }}
        run: docker stack deploy -c docker-compose.yml utsuki-bot
